### ISSUE TITLE
Featured Images in RSS Feed

### ISSUE THREAD

**Issue by thob** [medizinmedien/cc-medonline-at#2]
http://www.hughlashbrooke.com/2012/05/wordpress-add-featured-image-to-rss-feed/ bzw https://gist.github.com/hlashbrooke/5983688#file-function-php

Können wir das bitte asap einbauen und testen

**Comment by thob** [comment]
aber vermutlich besser ohne style

**Comment by hostz-frank** [comment]
Funktioniert zwar so nicht, habe daher den Code geändert und zum Laufen gebracht. Bitte mal gucken, ob das Ergebnis so OK ist für Dich: https://medonline.at/feed/

**Comment by thob** [comment]
Geht es auch für medonline.at/schlagwort/dfp/feed? Bin unterwegs und kann leider nicht testen

**Comment by hostz-frank** [comment]
> Geht es auch für medonline.at/schlagwort/dfp/feed?

Ja, tut da auch.

**Comment by thob** [comment]
Hi Frank, wir brauchen eine Formatierung für den Thumbnail. Szeanario: wir produzieren auf Basis des RSS Feeds automatische E-Mails. Das Template in Mailchimp schnappt sich Titel, Exzerpt, Thumbnail. Leider wollen Clients wie Outlook das CSS nicht verstehen. Der Autor des Templates meinte daher
>Since we are pulling the image and text from the feed, I have limited 
control over the formatting in some email clients.
Outlook and a few others strip code out or just ignore it. A possible 
solution would be adding attribute **align="right"** to the image in the 
feed.
The function you are using in wordpress to push the featured image into 
the feed should allow you to add a little bit of formatting

Kannst du das der Funktion hier mitgeben?

**Comment by hostz-frank** [comment]
2 Dinge nachgefragt, bitte: 
* `valign="left"` oder `valign="right"`?
* Soll z.B. `hspace="10"` als Quasi-Abstandhalter zum Text dazugegeben werden? (Keine Ahnung allerdings, was MS-Produkte damit machen ...) - andernfalls dürfte der Text wahrscheinlich am Bild "kleben".

**Comment by thob** [comment]
align=right, und vermutlich macht hspace (und ev. vspace) durchaus Sinn. Muss man ausprobieren und schauen, was Outlook draus macht.

So soll es aussehen > http://www.webfly.com/clients/medizin/2/

**Comment by thob** [comment]
any news?

**Comment by hostz-frank** [comment]
Ist soweit einmal getan.

https://github.com/medizinmedien/cc-medonline-at/commit/1b4de1739f14cd3e4ac7eb205243bf8c30356da9

**Comment by thob** [comment]
:+1: danke, @SimonAlm kannst mal testen, soabld ein neues dfp-getaggeder Beitrage veröffentlicht wird, sollte sich die Kampagne ändern und damit auch die Positionierung der Bildern in Outlook

**Comment by SimonAlm** [comment]
ok, beitrag wird heute oder morgen kommen

**Comment by thob** [comment]
klappt noch nicht in Mailchimp.Der Text soll neben dem Thumbnail stehe
![dfp-nl](https://cloud.githubusercontent.com/assets/755337/7298087/9311d3bc-e9cd-11e4-9c10-efb1b5738d64.png)

**Comment by hostz-frank** [comment]
> klappt noch nicht in Mailchimp

Ist das durchgängig so wie in der Abbildung für diesen einen Artikel? Gibt's einen Online-Link, damit ich mir im Quelltext ansehen kann, was von der guten Absicht übrig geblieben ist?

**Comment by thob** [comment]
bitte noch warten, es kommt noch eine neue TemplateVersion vom Entwickler, hab dir via MC mal einen test geschickt.

**Comment by thob** [comment]
wobei ich hab jetzt den Verdacht, dass möglicherweise deine Änderungen dafür verantwortlich sind.

**Comment by hostz-frank** [comment]
Im Thunderbird sieht das so aus:

![thunder](https://cloud.githubusercontent.com/assets/6112236/7300670/d8470d2a-e9dd-11e4-8a67-fd2d47056932.png)

Allerdings sieht die Mail auch in Gmail so aus wie auf Deinem Screenshot. Das liegt daran, dass das HTML-Dokument als HTML5 definiert ist - und das kennt kein Attribut "valign" für das img-Element. Ich glaube, dass Mailchimp da etwas anderes macht, als was sich der Autor des Templates denkt. Also das mit dem valign kann mit HTML5 nicht gehen; vielleicht sollte man mal Mailchimp fragen, wie man Bilder floaten lassen kann - ist ja ihr Geschäft das zu wissen.

**Comment by hostz-frank** [comment]
> wobei ich hab jetzt den Verdacht, dass möglicherweise deine Änderungen dafür verantwortlich sind

Es sind Deine Änderungswünsche, die ich lediglich umgesetzt habe, wenn wir oben nachlesen. Ich habe weder mit Maichimp noch mit Outlook Erfahrung und kann diesbzgl. leider gar nichts verantworten :-)

**Comment by thob** [comment]
Hab ein neues Template vom Autor bekommen, zusätzlich schreibt er
>
I've attached updated zip file for template.
Plus the styling on the image in your feed is wrong.
>
You have:
>
`<img xmlns="http://www.w3.org/1999/xhtml" width="150" vspace="10" valign="right" hspace="10" height="150" alt="haut_gross" class="attachment-thumbnail wp-post-image" src="https://medonline.at/wp-content/uploads/haut_gross-150x150.jpg" xml:base="https://medonline.at/schlagwort/dfp/feed/" />`
>
It should be:
>
`<img xmlns="http://www.w3.org/1999/xhtml" width="150" vspace="0" align="right" hspace="0" height="150" alt="haut_gross" class="attachment-thumbnail wp-post-image" src="https://medonline.at/wp-content/uploads/haut_gross-150x150.jpg" xml:base="https://medonline.at/schlagwort/dfp/feed/" />`

**Comment by thob** [comment]
Wenn ich valign zu align ändere, dann geht's in Gmail wenigstens

**Comment by hostz-frank** [comment]
Vertical align: right :-)  Asche auf mein Haupt.

Bin neugierig, wie's jetzt aussieht.

**Comment by thob** [comment]
wir müssen schauen, wie wir den Feed befüttern, der nächste Content ist noch nicht fertig.

**Comment by hostz-frank** [comment]
https://medonline.at/schlagwort/dfp/feed/ sieht gut aus, in diesem Sinne.

**Comment by thob** [comment]
ich denk wir sind langsam dort, es fehlt noch ein wenig hspace rechts
![mc-dfp](https://cloud.githubusercontent.com/assets/755337/7315728/7d227220-ea70-11e4-9a88-e3cfff3b9daa.png)

**Comment by hostz-frank** [comment]
`hspace` geht nur rechts **und** links. Ich geb mal 10px, oder?

**Comment by hostz-frank** [comment]
@SimonAlm - Ich dachte, ich hab's schon gemacht - war aber nicht der Fall. Ab jetzt dann also.

**Comment by hostz-frank** [comment]
Ich schließe das einmal - scheint ja jetzt OK zu sein.
