### ISSUE TITLE
no thumb rating für Kategorie Quiz

### ISSUE THREAD

**Issue by thob** [medizinmedien/cc-medonline-at#3]
bitte

**Comment by hostz-frank** [comment]
@SimonAlm - Kann ich bitte eine URL haben, wo das im Einsatz ist und an welcher Stelle dann dort das Rating erscheinen soll? Polls hat irgendein Templating-System: was/ welches nutzt Ihr da?

**Comment by SimonAlm** [comment]
frank, es geht soweit ich das verstanden habe darum, dass dort die thumbs NICHT zu sehen sein sollen:
beispiel hier, mit demumfrage plugin kommt dann der embed.
 http://medonline.at/2015/bdw13/

**Comment by thob** [comment]
:+1:

**Comment by hostz-frank** [comment]
Geht schon. 
Und WOW - die Idee schlägt ja ein wie eine Bombe: schon **238 Stimmen** (oder ist das nur ein Test? ...)
